// Bakes every clay bus image from code. Run: node shared/buses/export.mjs   (then: node shared/sync.js)
// Opens export.html in headless Edge/Chrome (software WebGL), reads the rendered images back out of the page,
// writes them to shared/buses/out/ and regenerates the image index modules. Needs network once for three.js (CDN).
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const browser = [
  process.env.BROWSER_PATH,
  'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', 'C:/Program Files/Microsoft/Edge/Application/msedge.exe',
  'C:/Program Files/Google/Chrome/Application/chrome.exe', '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/usr/bin/google-chrome', '/usr/bin/chromium', '/usr/bin/chromium-browser',
].find((p) => p && existsSync(p));
if (!browser) throw new Error('No Edge or Chrome found. Set BROWSER_PATH to a Chromium-based browser.');

const profile = mkdtempSync(join(tmpdir(), 'smartbus-export-'));
let dom;
try {
  dom = execFileSync(browser, ['--headless=new', '--enable-unsafe-swiftshader', '--use-angle=swiftshader', '--ignore-gpu-blocklist', `--user-data-dir=${profile}`,
    '--virtual-time-budget=120000', '--dump-dom', pathToFileURL(join(here, 'export.html')).href], { encoding: 'utf8', maxBuffer: 512 * 1024 * 1024, stdio: ['ignore', 'pipe', 'ignore'] });
} finally { rmSync(profile, { recursive: true, force: true }); }
if (!dom.includes('data-done="1"')) throw new Error('The export page did not finish rendering (WebGL unavailable, or three.js could not load).');

const images = [...dom.matchAll(/<img data-name="([\w-]+)" src="data:image\/webp;base64,([^"]+)"/g)].map(([, name, b64]) => ({ name, b64 }));
if (images.length < 40) throw new Error(`Expected at least 40 images, found ${images.length}.`);

const out = join(here, 'out');
mkdirSync(out, { recursive: true });
for (const f of readdirSync(out)) rmSync(join(out, f));
const files = images.filter((i) => !i.name.startsWith('marker-'));
let bytes = 0;
for (const { name, b64 } of files) { const buf = Buffer.from(b64, 'base64'); bytes += buf.length; writeFileSync(join(out, `${name}.webp`), buf); }

const banner = '// GENERATED by shared/buses/export.mjs — do not edit by hand.\n';
const id = (n) => n.replace(/-(\w)/g, (_, ch) => ch.toUpperCase());
// Native: static require() per image, resolved from apps/*/src/components/.
writeFileSync(join(here, '..', 'native', 'busImages.js'), `${banner}export const IMAGES = {\n${files.map((f) => `  '${f.name}': require('../../assets/buses/${f.name}.webp'),`).join('\n')}\n};\n`);
// Web: one import per image, resolved from apps/admin-dashboard/src/design/.
writeFileSync(join(here, '..', 'web', 'busImages.js'), `${banner}${files.map((f) => `import ${id(f.name)} from './buses/${f.name}.webp';`).join('\n')}\n\nexport const IMAGES = {\n${files.map((f) => `  '${f.name}': ${id(f.name)},`).join('\n')}\n};\n`);
// Markers are small enough to inline, which is also what the Leaflet page string needs. Index = compass heading / 45.
const markers = images.filter((i) => i.name.startsWith('marker-')).sort((a, b) => a.name.localeCompare(b.name));
writeFileSync(join(here, '..', 'busMarkers.js'), `${banner}export const MARKERS = [\n${markers.map((mk) => `  'data:image/webp;base64,${mk.b64}',`).join('\n')}\n];\n`);

console.log(`${files.length} images (${Math.round(bytes / 1024)} KB) → shared/buses/out, ${markers.length} markers (${Math.round(markers.reduce((n, mk) => n + mk.b64.length, 0) * 0.75 / 1024)} KB) → shared/busMarkers.js`);
