// GENERATED by shared/buses/export.mjs — do not edit by hand.
import busGreenRunning from './buses/bus-green-running.webp';
import busGreenIdle from './buses/bus-green-idle.webp';
import busGreenParked from './buses/bus-green-parked.webp';
import busTealRunning from './buses/bus-teal-running.webp';
import busTealIdle from './buses/bus-teal-idle.webp';
import busTealParked from './buses/bus-teal-parked.webp';
import busCoralRunning from './buses/bus-coral-running.webp';
import busCoralIdle from './buses/bus-coral-idle.webp';
import busCoralParked from './buses/bus-coral-parked.webp';
import busYellowRunning from './buses/bus-yellow-running.webp';
import busYellowIdle from './buses/bus-yellow-idle.webp';
import busYellowParked from './buses/bus-yellow-parked.webp';
import busOrangeRunning from './buses/bus-orange-running.webp';
import busOrangeIdle from './buses/bus-orange-idle.webp';
import busOrangeParked from './buses/bus-orange-parked.webp';
import busPurpleRunning from './buses/bus-purple-running.webp';
import busPurpleIdle from './buses/bus-purple-idle.webp';
import busPurpleParked from './buses/bus-purple-parked.webp';
import busNavyRunning from './buses/bus-navy-running.webp';
import busNavyIdle from './buses/bus-navy-idle.webp';
import busNavyParked from './buses/bus-navy-parked.webp';
import busRedRunning from './buses/bus-red-running.webp';
import busRedIdle from './buses/bus-red-idle.webp';
import busRedParked from './buses/bus-red-parked.webp';
import busMintRunning from './buses/bus-mint-running.webp';
import busMintIdle from './buses/bus-mint-idle.webp';
import busMintParked from './buses/bus-mint-parked.webp';
import busCreamRunning from './buses/bus-cream-running.webp';
import busCreamIdle from './buses/bus-cream-idle.webp';
import busCreamParked from './buses/bus-cream-parked.webp';
import busOff from './buses/bus-off.webp';
import coachCoralRunning from './buses/coach-coral-running.webp';
import coachCoralIdle from './buses/coach-coral-idle.webp';
import coachMintRunning from './buses/coach-mint-running.webp';
import coachMintIdle from './buses/coach-mint-idle.webp';
import minibusMintRunning from './buses/minibus-mint-running.webp';
import minibusMintIdle from './buses/minibus-mint-idle.webp';
import minibusCoralRunning from './buses/minibus-coral-running.webp';
import minibusCoralIdle from './buses/minibus-coral-idle.webp';
import schoolYellowRunning from './buses/school-yellow-running.webp';
import schoolYellowIdle from './buses/school-yellow-idle.webp';
import deckerRedRunning from './buses/decker-red-running.webp';
import deckerRedIdle from './buses/decker-red-idle.webp';
import driverCoralIdle from './buses/driver-coral-idle.webp';
import routeMintIdle from './buses/route-mint-idle.webp';
import sceneLogin from './buses/scene-login.webp';
import sceneRegister from './buses/scene-register.webp';
import sceneDriver from './buses/scene-driver.webp';
import sceneAdmin from './buses/scene-admin.webp';

export const IMAGES = {
  'bus-green-running': busGreenRunning,
  'bus-green-idle': busGreenIdle,
  'bus-green-parked': busGreenParked,
  'bus-teal-running': busTealRunning,
  'bus-teal-idle': busTealIdle,
  'bus-teal-parked': busTealParked,
  'bus-coral-running': busCoralRunning,
  'bus-coral-idle': busCoralIdle,
  'bus-coral-parked': busCoralParked,
  'bus-yellow-running': busYellowRunning,
  'bus-yellow-idle': busYellowIdle,
  'bus-yellow-parked': busYellowParked,
  'bus-orange-running': busOrangeRunning,
  'bus-orange-idle': busOrangeIdle,
  'bus-orange-parked': busOrangeParked,
  'bus-purple-running': busPurpleRunning,
  'bus-purple-idle': busPurpleIdle,
  'bus-purple-parked': busPurpleParked,
  'bus-navy-running': busNavyRunning,
  'bus-navy-idle': busNavyIdle,
  'bus-navy-parked': busNavyParked,
  'bus-red-running': busRedRunning,
  'bus-red-idle': busRedIdle,
  'bus-red-parked': busRedParked,
  'bus-mint-running': busMintRunning,
  'bus-mint-idle': busMintIdle,
  'bus-mint-parked': busMintParked,
  'bus-cream-running': busCreamRunning,
  'bus-cream-idle': busCreamIdle,
  'bus-cream-parked': busCreamParked,
  'bus-off': busOff,
  'coach-coral-running': coachCoralRunning,
  'coach-coral-idle': coachCoralIdle,
  'coach-mint-running': coachMintRunning,
  'coach-mint-idle': coachMintIdle,
  'minibus-mint-running': minibusMintRunning,
  'minibus-mint-idle': minibusMintIdle,
  'minibus-coral-running': minibusCoralRunning,
  'minibus-coral-idle': minibusCoralIdle,
  'school-yellow-running': schoolYellowRunning,
  'school-yellow-idle': schoolYellowIdle,
  'decker-red-running': deckerRedRunning,
  'decker-red-idle': deckerRedIdle,
  'driver-coral-idle': driverCoralIdle,
  'route-mint-idle': routeMintIdle,
  'scene-login': sceneLogin,
  'scene-register': sceneRegister,
  'scene-driver': sceneDriver,
  'scene-admin': sceneAdmin,
};
