// Copies the design system into every app and generates the admin's CSS tokens.  Run: node shared/sync.js
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { COLORS, RADII, SPACE, TYPE, SHADOWS } from './tokens.js';

const here = dirname(fileURLToPath(import.meta.url));
const apps = join(here, '..', 'apps');
const put = (from, to) => { mkdirSync(dirname(to), { recursive: true }); copyFileSync(join(here, from), to); console.log('→', to.replace(join(here, '..'), '')); };

for (const app of ['passenger-app', 'driver-app']) {
  put('tokens.js', join(apps, app, 'src/constants/theme.js'));
  put('vehicleShapes.js', join(apps, app, 'src/components/vehicleShapes.js'));
  put('native/ui.js', join(apps, app, 'src/components/ui.js'));
  put('native/LiveMap.js', join(apps, app, 'src/components/LiveMap.js'));
  put('native/LiveMap.native.js', join(apps, app, 'src/components/LiveMap.native.js'));
  put('native/api.js', join(apps, app, 'src/api.js'));
}
const admin = join(apps, 'admin-dashboard/src/design');
put('vehicleShapes.js', join(admin, 'vehicleShapes.js'));
put('web/Vehicle.js', join(admin, 'Vehicle.js'));

const kebab = (s) => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
const shadow = (s) => `0 ${s.shadowOffset.height}px ${s.shadowRadius}px rgba(31, 58, 86, ${s.shadowOpacity})`;
const lines = [
  '/* GENERATED by shared/sync.js from shared/tokens.js — do not edit by hand. */',
  ':root {',
  ...Object.entries(COLORS).filter(([k, v]) => typeof v === 'string' && !/^(bg[A-Z]|border|text|accentOrange|accentBlue|accentDark|successLight|warningLight|dangerLight|white|black)/.test(k))
    .map(([k, v]) => `  --${kebab(k)}: ${v};`),
  ...Object.entries(COLORS.tints).flatMap(([k, [a, b]]) => [`  --tint-${k}-from: ${a};`, `  --tint-${k}-to: ${b};`]),
  ...Object.entries(RADII).map(([k, v]) => `  --radius-${k}: ${v}px;`),
  ...Object.entries(SPACE).map(([k, v]) => `  --space-${k}: ${v}px;`),
  ...Object.entries(SHADOWS).map(([k, v]) => `  --shadow-${k}: ${shadow(v)};`),
  ...Object.entries(TYPE).flatMap(([k, t]) => [
    `  --fs-${kebab(k)}: ${t.fontSize}px;`, `  --lh-${kebab(k)}: ${t.lineHeight}px;`, `  --fw-${kebab(k)}: ${t.fontWeight};`,
  ]),
  '  --ease-out: cubic-bezier(0.23, 1, 0.32, 1);',
  '  --touch: 44px;',
  '}',
];
writeFileSync(join(admin, 'tokens.css'), lines.join('\n') + '\n');
console.log('→ admin tokens.css');
